name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest
      - name: Build Docker Image
        run: docker build -t your-docker-repo/your-image-name:latest .

    #   - name: Push Docker Image
    #     run: |
    #       echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    #       docker push your-docker-repo/your-image-name:latest

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: SSH and Deploy
#         uses: appleboy/ssh-action@v0.1.5
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_KEY }}
#           script: |
#             docker pull your-docker-repo/your-image-name:latest
#             docker stop your-container-name
#             docker rm your-container-name
#             docker run -d --name your-container-name your-docker-repo/your-image-name:latest
